name: Automated Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-unit:
    name: Test Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Test Unit
        run: pnpm run test
