name: Code Quality Checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run format:check

  check-linting:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Check linting
        run: pnpm run lint

  check-type-safety:
    name: Check Type Safety
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Check type safety
        run: pnpm run typecheck

  check-unused-code:
    name: Check unused code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Check unused code
        run: pnpm run knip
